A storage update (server-side)
openstadia/openstadia-storage pull request #1
Opened 2023-11-28 18:06 UTC by greenem-official

2023-11-29 12:35 UTC, erlnby requested changes

2023-11-29 12:35 UTC, erlnby commented on go.mod
>  module github.com/openstadia/openstadia-storage
Выполнить команду go mod tidy для определения direct ависимостей

2023-11-29 12:35 UTC, erlnby commented on main.go
> +		// some important settings are not set, no reason to continue
Добавить сообщение об проблеме с инициализацией конфига, например log.Fatal

2023-11-29 12:35 UTC, erlnby commented on hub_operations/authorization.go
> +	req, err := http.NewRequest("GET", configuration.Settings.HubDomain+"/users/me", nil)
лучше собирать tring с использованием fmt.Sprintf

2023-11-29 12:35 UTC, erlnby commented on hub_operations/authorization.go
> +		return nil, errors.New("Error on http.NewRequest():\n" + err.Error())
Изучи правила именования ошибок в Go и поменяй, согласно им

2023-11-29 12:35 UTC, erlnby commented on hub_operations/authorization.go
> +		return nil, errors.New("Error on client.Do(request):\n" + err.Error())
То же

2023-11-29 12:35 UTC, erlnby commented on hub_operations/authorization.go
> +	decoder := json.NewDecoder(res.Body)
Почему просто не использовать json.Unmarshal?

2023-11-29 12:35 UTC, erlnby commented on hub_operations/authorization.go
> +		return nil, nil
Тут ошибка должна вернуться

2023-11-29 12:35 UTC, erlnby commented on models/files.go
> +type DeleteFile struct {
DeleteFiles?

2023-11-29 12:35 UTC, erlnby commented on models/minio.go
> +	Size       uint64    `json:"sizeTotal"`
json snake case

2023-11-29 12:35 UTC, erlnby commented on models/minio.go
> +	// this would always be called with the general info request nearby, so it would retrieve and iterate files twice
Зачем этот комментарий?

2023-11-29 12:35 UTC, erlnby commented on models/minio.go
> +type StorageInfo struct {
Наверное этот объект можно включить как поле в ObjectList

2023-11-29 12:35 UTC, erlnby commented on models/user.go
> +	AllowedTotalSpace     uint64 `json:"total_space_available" binding:"required"`
Разные названия полей

2023-11-29 12:35 UTC, erlnby commented on configuration/config.go
> +func Init() bool {
Наверное, при ошибке инициализции поля возвращать ошибку.
Также лучше возвращать сам объект конфига

2023-11-29 12:35 UTC, erlnby commented on configuration/config.go
> +var Settings TypeStorageSettings
Лучше не делать такие глобальные переменные

2023-11-29 12:35 UTC, erlnby commented on configuration/config.go
> +			print("Config parameter '" + key + "' is not set!")
print метод deprecated, используй fmt.Printld

2023-11-29 12:35 UTC, erlnby commented on configuration/config.go
> +func tryToLoadValue(key string, target *string, printWarnings bool) bool {
Возвращай ошибку

2023-11-29 12:35 UTC, erlnby commented on connection/crud/database.go
> +func GetStorageUserInfo(u *models.HubUser) models.StorageUserInfo {
const (
	KiB = 1024
	MiB = 1024 * KiB
	GiB = 1024 * MiB
	TiB = 1024 * GiB
	PiB = 1024 * TiB
)

2023-11-29 12:35 UTC, erlnby commented on connection/crud/database.go
> +	// placeholder
Лучше возвращать отключенное состояние, чем сломать прод в таком случак

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/bolt_operations/bolt_operations.go
> +package bolt_operations
Зачем расплодил так много packages?

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/bolt_operations/Qotas.go
> +package bolt_operations
Название файлов с маленькоой буквы

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/bolt_operations/Qotas.go
> +		return 1024 * 1024 * 1024 // 1 GB
Size constants

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/bolt_operations/Qotas.go
> +	case "default":
Что за константа?

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	return "user-" + strconv.Itoa(u.Id)
Sprintf

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +func BROKEN_DeleteMultipleFiles(u *models.HubUser, files models.DeleteFile) ([]models.UnsuccessfulFileOperation, []error) {
Удали. если не используктся

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +		//ctx2, cancel2 := context.WithCancel(context.Background())
Удали комментарии

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +func CreateBucketIfNeeded(u *models.HubUser) error {
Название не соответствует происходящему внутри. Помимо создания бакета тут ещё происходит установка квоты для пользователя.

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +func GetUserFilesList(u *models.HubUser) (*models.ObjectsList, error) {
Зачем у тебя во всех методах HubUser, если вся твоя система работает со своим представлением пользователя?

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +		result.Objects = []models.StorageObject{}
Зачем проверка на это? Ты можешь сразу создать пустой массив?

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +func GetBucketQuota(u *models.HubUser) (*madmin.BucketQuota, error) {
То же самое про user

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	result := &models.StorageInfo{}
Зачем создавать жту переменную заранее? Инициализируй непосредственно перед использованием

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	result.UsedSpace = 0
У тебя эти данные вычисляются в GetUserFilesList

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	var failedOperations = []models.UnsuccessfulFileOperation{} // code analysis tools say to replace this, but then it will be initially null
Используй метод make([]models.UnsuccessfulFileOperation, 0) чтобы создать пустой массив

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	var exactErrors []error
Никогда не виел.ю чтобы массив ошибок создавали

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +func DeleteFiles(u *models.HubUser, files models.DeleteFile) ([]models.UnsuccessfulFileOperation, []error) {
Зачем метод с удалением нескольких обхектов, если все равно они удаляются по одному?

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +		err := connections.Client.RemoveObject(ctx, GetUserBucketName(u), path, minio.RemoveObjectOptions{}) // ForceDelete??? It's not documented
Вынеси метод для удалния одного файла

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	//if len(failedOperations) == 0 {
Удаляй комментарии

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	presignedURL, err := connections.Client.PresignedGetObject(context.Background(), GetUserBucketName(u), file.Path, configuration.OperationSettings.FileDownloadLinksExpiration, reqParams)
Ctrl + Alt + L

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +	reqParams.Set("response-content-disposition", "attachment; filename=\""+file.Path+"\"")
sprintf

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +		return nil, errors.New("The file already exists!")
Обика может быть только из-за этого?

2023-11-29 12:35 UTC, erlnby commented on connection/connections/operations/minio_operations/minio_operations.go
> +func UploadFile(u *models.HubUser, file models.UploadFile) (*url.URL, error) { // later think about downloading multiple in an archive
Не оставляй такие комментарии, они никому не нужны

2023-11-29 12:35 UTC, erlnby commented on connection/connections/bolt_connection.go
> +var Database *bolt.DB
Не делай глобальные переменные

2023-11-29 12:35 UTC, erlnby commented on connection/connections/minio_connection.go
> +var Client *minio.Client
Не делай глобальные переменные

2023-11-29 12:35 UTC, erlnby commented on connection/connections/minio_connection.go
> +		return errors.New("failed to initialize the MinIO client connection:\n" + err.Error())
Error naming conversation

2023-11-29 12:35 UTC, erlnby commented on connection/connections/minio_connection.go
> +		return errors.New("failed to initialize the Madmin client connection:\n" + err.Error())
Error naming conversation

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/storage/storage_api.go
> +	r := mux.NewRouter()
Если у тебя во всех методах используется авторизация, то нельзя её вынести как middleware ля всех путей?

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/storage/storage_api.go
> +		log.Println("Error at checking if a bucket exists:\n" + err.Error())
sprintf

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/storage/storage_api.go
> +	if !tryToCreateStorage(w, u) {
Наверное, до этого момента storage же должен быть создан и тут это проверять не нужно

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/storage/storage_api.go
> +	list, err := minio_operations.GetUserFilesList(u)
У тебя же есть метод, который объединяет эти два действия

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/storage/storage_api.go
> +func getOnlyGeneralStorageInfo(w http.ResponseWriter, _ *http.Request, u *models.HubUser) {
Зачем слово only?

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/utils.go
> +	err := json.NewEncoder(w).Encode(target)
json marshal

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/utils.go
> +	decoder.DisallowUnknownFields()
json unmarshal

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/utils.go
> +		w.WriteHeader(http.StatusBadRequest)
unprocessable entity

2023-11-29 12:35 UTC, erlnby commented on connection/routing/api/storage/storage_api.go
> +	// | broken way |
Удаляй коментарии

2023-11-29 12:35 UTC, erlnby commented on connection/routing/authentification/request_authentification.go
> +	u, err := hub_operations.Authorize(r.Header.Get("Authorization"))
Наверное в этом методе стоит сразу запрашивать и нашего внутреннего пользователя

2023-11-30 14:07 UTC, DaylightDragon commented on main.go
> +		// some important settings are not set, no reason to continue
Такое сообщение уже выводится внутри Init() с указанием на конкретную проблему

2023-11-30 14:08 UTC, greenem-official commented on main.go
> +		// some important settings are not set, no reason to continue
Такое сообщение уже выводится внутри Init() с указанием конкретной проблемы

2023-11-30 15:11 UTC, greenem-official commented on hub_operations/authorization.go
> +		return nil, nil
Не совсем, так там вернётся ошибка о некорректных для HubUser полях, из-за того, что Hub отправил "Bad credentials", и я решил для этого специально создать случай, когда не вернётся ошибки (которая есть только в случае внутренних и непредвиденных, даёт HTTP 500), но при этом не вернётся никакого пользователя, и тогда это "Bad credentials". Ну а если вернулся пользователь и не вернулось ошибки, то всё нормально.
Но авторизацию я теперь всё равно немножно подправил внешне.

2023-11-30 15:41 UTC, greenem-official commented on hub_operations/authorization.go
> +	decoder := json.NewDecoder(res.Body)
Body запроса здесь это Reader, т.е. ещё не прочтённые данные, а json.Unmarshal принимает []byte, и вроде как лучше всего в таких случаях использовать json.NewDecoder

2023-11-30 15:45 UTC, greenem-official commented on models/minio.go
> +	// this would always be called with the general info request nearby, so it would retrieve and iterate files twice
Зачем-то решил попытаться так ответить на возможный тут вопрос "почему тут возвращается ещё и объём хранилища"

2025-01-10 10:55 UTC, closed without merging